### ISSUE TITLE
Dry run doesn't care about RUN_MODE

### ISSUE THREAD

**Issue by netflash** [hellofresh/eks-rolling-update#108]
Hi there,

I've been using this tool for a while. And recently the dry-run behaviour changed.
Unfortunately, I can't say what version introduced this though :-(

I have the `RUN_MODE` set to `1`, but when I run the tool with `-p` cli key, it runs in `RUN_MODE`=`4`.

Expected behaviour:
dry run pays attention to the RUN_MODE variable

**Comment by georambo** [comment]
i've seen the same issue.

**Comment by pysysops** [comment]
This is fixed by #99

**Comment by crhuber** [comment]
Fixed by https://github.com/hellofresh/eks-rolling-update/pull/99
