### ISSUE TITLE
Missing cordon on outdated nodes

### ISSUE THREAD

**Issue by msvticket** [hellofresh/eks-rolling-update#13]
This script seems to be useful and in general do the right thing. But I think one step is missing for the smoothest operation: All the outdated nodes should be cordoned just before draining them. Otherwise pods might be migrated to other outdated nodes when a node is drained, which means then they would be migrated more than once during the rolling update.

**Comment by crhuber** [comment]
@msvicket thanks ! Adding that now

**Comment by crhuber** [comment]
@msvticket it seems the kubectl drain command also runs a cordon before running, so I believe we are covered already
https://github.com/kubernetes/kubernetes/blob/ca89308227abdf4f2c895118528c354c32aa3046/pkg/kubectl/cmd/drain.go#L239

**Comment by nicolasbelanger** [comment]
@crhuber I believe @msvticket is right here.  It's true that drain will cordon, but the suggestion here is to make sure that the new pods are scheduled on a fresh node, which is not guaranteed if you drain one-by-one.  The suggestion here is to cordon all the outdated nodes at once when the scale-up happened successfully.  However, if the cluster is deployed across multiple ASG, there's still a possibility that the pods will be scheduled onto an ASG that's not been rolled out just yet, but that's still a fair price to pay here.

**Comment by crhuber** [comment]
@nicolasbelanger i get it, i will try adding that feature

**Comment by nicolasbelanger** [comment]
@cablespaghetti Thanks for this ;).  I have a concern though about having all the nodes cordoned before any fresh node is available.  Isn't it dangerous to have no nodes to schedule on if the process hangs for some reason?

**Comment by cablespaghetti** [comment]
It's what I've always done when doing this by hand, but yes you raise a good point. Maybe we want to do the scaling up (for all ASGs), then all the cordoning, then the rest of the process?

**Comment by cablespaghetti** [comment]
AWS limits are definitely a potential issue. I've implemented the doing it all at once approach now anyway: https://github.com/cablespaghetti/eks-rolling-update/blob/feature/cordon/eks_rolling_update.py

The commit before that has the cordon everything first and then do everything else per ASG approach.

I'm going to have to put this down due to time constraints now anyway. I might pick it up in a few days and see if I can refactor things a bit to make it non-messy to give the user options.

**Comment by nicolasbelanger** [comment]
👍 for a parameter that allows either the all-in or per-asg method ;)
