### ISSUE TITLE
Values from ENV are being used as int and bool

### ISSUE THREAD

**Issue by mbrannigan** [hellofresh/eks-rolling-update#23]
`K8S_AUTOSCALER_ENABLED` and `DRY_RUN` are being used as `bool` values in the code
`CLUSTER_HEALTH_WAIT`, `GLOBAL_MAX_RETRY`, `GLOBAL_HEALTH_WAIT`, `BETWEEN_NODES_WAIT`, and `RUN_MODE` are being used as `int` values.

Code will need to cast them appropriately.

**Comment by mbrannigan** [comment]
Opened PR https://github.com/hellofresh/eks-rolling-update/pull/24

**Comment by crhuber** [comment]
resolved in #24
