### ISSUE TITLE
Allow Configurable Replica Count for Cluster Autoscaler

### ISSUE THREAD

**Issue by livingeek** [hellofresh/eks-rolling-update#25]
In the code resuming the cluster autoscaler is hard coded to 2 replicas.  In our environment we only run a single replica.  Since running multiple replicas is untested in our environment we manually reset it to replica=1 after running the rolling update.  

It would be nice to have the option to pass in a value for cluster autoscaler replicas.  I imagine that there are other people running either a single instance or more than two replicas that would benefit from this.

**Comment by crhuber** [comment]
@livingeek good suggestion. I'll try to add that thanks
