### ISSUE TITLE
unable to install eks-rolling-update from pip or pip3

### ISSUE THREAD

**Issue by nagendrm** [hellofresh/eks-rolling-update#46]
I have installed the latest python3 and tried to install this module from pip and pip3 both. 

**trial-1**
root@ip-10-XX-XX-XX:/home/ubuntu/eks-rolling-update# pip3 install eks-rolling-update
ERROR: Could not find a version that satisfies the requirement eks-rolling-update (from versions: none)
ERROR: No matching distribution found for eks-rolling-update

**trial-2**
root@ip-10-XX-XX-XX:/home/ubuntu/eks-rolling-update# pip3 install "eks-rolling-update==1.0.96"
ERROR: Could not find a version that satisfies the requirement eks-rolling-update==1.0.96 (from versions: none)
ERROR: No matching distribution found for eks-rolling-update==1.0.96

**trial-3 - downloaded the tar.gz file and tried installing through pip3 install**
root@ip-10-XX-XX-XX:/home/ubuntu/eks-rolling-update# pip3 install eks-rolling-update-1.0.96.tar.gz
Processing ./eks-rolling-update-1.0.96.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-n36f_y60/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-n36f_y60/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4fa6hv6b
         cwd: /tmp/pip-req-build-n36f_y60/
    Complete output (32 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-n36f_y60/setup.py", line 7, in <module>
        setuptools.setup()
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 494, in parse_config_files
        ignore_option_errors=ignore_option_errors)

**trial-4**
root@ip-10-XX-XX-XX:/home/ubuntu/eks-rolling-update# pip3 install eks-rolling-update --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org
ERROR: Could not find a version that satisfies the requirement eks-rolling-update (from versions: none)
ERROR: No matching distribution found for eks-rolling-update

**I am not able to find any other method to install this module. I have latest TLS=1.3 and if you could help me install this module, it will be a great help.**

**Comment by chadlwilson** [comment]
Hi @nagendrm - could you please confirm

- the output of `pip3 debug` (basically specific python version, pip version and arch if it doesn't work)
- the output of `pip3 install -vvv eks-rolling-update`

I tried installing on a clean `Ubuntu 20.04 LTS (Focal Fossa)` docker image with `apt-get install python3 python3-pip` and it worked OK for me

**Comment by nagendrm** [comment]
I am able to install the eks-rolling-update on ubuntu image now. I am able to pass the first step. i am kind of stuck on how to use this utility. i did run the docker container and i can find eks-rolling-update.py on /usr/local/bin path. when i run the python file like this, it is throwing error:

**error:**
python3.8 /usr/local/bin/eks_rolling_update.py -h
Traceback (most recent call last):
  File "/usr/local/bin/eks_rolling_update.py", line 5, in <module>
    from eksrollup.cli import main
ModuleNotFoundError: No module named 'eksrollup'

Is this the correct way to run or please suggest the right way to run this utility. Thanks

**Comment by chadlwilson** [comment]
It sounds like you have switched methodologies rather than focusing on the issue you first raised and supplying the requested information, which is a bit confusing to me.

In any case, the [README](https://github.com/hellofresh/eks-rolling-update/blob/master/README.md) indicates how to run using a built docker image as a black-box without having to understand the details of Python module loading.

**Comment by nagendrm** [comment]
Thanks for the response. please excuse my confusions. I have figured out the way to run the utililty now. I want to know if there is a way to update the AMI ID on the launch configuration from this utility, that will help me achieve my requirement. I believe this a great utility you guys have developed.

**Comment by chadlwilson** [comment]
That's mainly the HelloFresh team :-) I am just an occasional contributor, and I helped with the Python packaging, which is why I was trying to help debug here.

This utility won't touch/edit your launch configuration/launch template, it will just compare the launch configuration name or the launch template name/version between that on the ASG and each individual existing instance in the ASG to determine whether any of the instances are out-of-date.

In our case, we modify the launch _template_ via Terraform before running this tool, however you can test it with launch configurations by changing the configuration via AWS CLI or console to a different one and then running the tool. If you run in `--plan` mode it should tell you what it's going to do before it does it.

**Comment by nagendrm** [comment]
We have run this utility on our cluster. Initially when we run it for the first time, it failed to terminate the ec2 nodes, so we manually scaled down the asg to zero nodes and scaled up to original count. then we made change to ami id again and triggered this utility. It fails will the below message everytime. I could see the nodes are health (ready status) and everything looks healthy on asg side. I could not understand why it is saying this below message everytime.

**Error:**
2020-06-05 21:09:19,551 INFO     Found 5 outdated instances
2020-06-05 21:09:19,611 INFO     Getting k8s nodes...
2020-06-05 21:09:19,940 INFO     Current k8s node count is 5
2020-06-05 21:09:19,941 INFO     Setting the scale of ASG my-cluster-node-asg based on 5 outdated instances.
2020-06-05 21:09:19,941 INFO     Modifying asg my-cluster-node-asg autoscaling to resume ...
2020-06-05 21:09:20,084 INFO     Found previous desired capacity value tag set on asg from a previous run.
2020-06-05 21:09:20,084 INFO     Maintaining previous capacity of 5 to not overscale.
2020-06-05 21:09:20,084 INFO     Describing autoscaling groups...
2020-06-05 21:09:20,432 INFO     Current asg instance count in cluster is: 5. K8s node count should match this number
2020-06-05 21:09:20,432 INFO     Checking asg my-cluster-node-asg instance count...
2020-06-05 21:09:20,536 INFO     Asg my-cluster-node-asg does not have enough running instances to proceed
2020-06-05 21:09:20,536 INFO     Actual instances: 5 Desired instances: 9
2020-06-05 21:09:20,536 INFO     Validation failed for asg my-cluster-node-asg. Not enough instances online.
2020-06-05 21:09:20,536 INFO     Exiting since ASG healthcheck failed
2020-06-05 21:09:20,536 ERROR    ASG healthcheck failed
2020-06-05 21:09:20,536 ERROR    *** Rolling update of ASG has failed. Exiting ***
2020-06-05 21:09:20,536 ERROR    AWS Auto Scaling Group processes will need resuming manually


Any pointer to help us will be much appreciated. Thanks in advance.

**Comment by chadlwilson** [comment]
It's probably a bit difficult for anyone to comment without understand your ASG setup, having the full log and any earlier runs, and knowing the modes/env vars you set while running the tool. What do you expect to happen? What does happen? What is the end state of the tags on the ASG?

It would probably help if you are able to debug the setup more methodically to determine which events are taking place on your instances at which times to determine what is going on.

Suggest that you correlate what you see the tool doing with anything you see on the ASG activity to determine whether the ASG is taking actions on instances for some reason that is confusing the tool's ability to know where it is up to.

**Comment by crhuber** [comment]
@nagendrm Thanks for reporting the issue. It seems you were able to install via pip now correct? The tool doesnt update the AMI on your launch config. For that I suggest something like terraform. The tool only compares the instance launch template/config to the asg template/config and draing/corondon/terminates it if out of date. 
It seems you have multiple issues in this thread. There have been some updates to the tool recently, so I suggest you try with latest and re-open a new issue. Closing this issue but feel free to re-open a new one if problem persists.

**Comment by GregVes** [comment]
> @nagendrm Thanks for reporting the issue. It seems you were able to install via pip now correct? The tool doesnt update the AMI on your launch config. For that I suggest something like terraform. The tool only compares the instance launch template/config to the asg template/config and draing/corondon/terminates it if out of date.
> It seems you have multiple issues in this thread. There have been some updates to the tool recently, so I suggest you try with latest and re-open a new issue. Closing this issue but feel free to re-open a new one if problem persists.

Hello! So in the case of a complete upgrade of a cluster, I would first need to bump the master and nodes k8s versions in the Terraform code AND then I could use your utility that will increase ASG (creates automatically new nodes with upgraded AMI), drain/cordon/ terminates the old nodes. Am I right?

**Comment by chadlwilson** [comment]
> Hello! So in the case of a complete upgrade of a cluster, I would first need to bump the master and nodes k8s versions in the Terraform code AND then I could use your utility that will increase ASG (creates automatically new nodes with upgraded AMI), drain/cordon/ terminates the old nodes. Am I right?

@GregVes broadly speaking, yes (if you don't want to use EKS managed node groups, and would prefer to manage them yourselves with this tool)
