### ISSUE TITLE
Tagging variables can not be customized

### ISSUE THREAD

**Issue by keelson** [hellofresh/eks-rolling-update#51]
The documentation in `README.md` states that
`ASG_DESIRED_STATE_TAG`
`ASG_ORIG_CAPACITY_TAG`
`ASG_ORIG_MAX_CAPACITY_TAG`

can be specified from the environment, but in https://github.com/hellofresh/eks-rolling-update/blob/master/eksrollup/config.py the variables are hardcoded. 

Is there any reason? 

Even though they are temporary, I'd like to customize them.

**Comment by crhuber** [comment]
@keelson there was no specific reason, I just didnt think there would be a need to customize at first. Fixed in latest
