### ISSUE TITLE
Clarify documentation on termination check

### ISSUE THREAD

**Issue by farhank3389** [hellofresh/eks-rolling-update#54]
The script timed out due to an instance taking longer than usual to terminate.

The environment variable that needs to be set to increase the number of checks is `GLOBAL_MAX_RETRY`. But the documentation says this is `Number of attempts of a health check`. However the termination check is not a health check and this documentation should be corrected to something like `Number of attempts of a health or termination check`.

**Comment by crosbymichael1** [comment]
I agree with your definition and I have experienced the same issue as well. I have addressed this in PR #58

**Comment by crhuber** [comment]
Fixed by #58
