### ISSUE TITLE
Why not the upgrade command 'eksctl upgrade cluster --name dev' ?

### ISSUE THREAD

**Issue by openstacker** [hellofresh/eks-rolling-update#59]
Hi there,  I mean new with this rolling upgrade tool, so my question may be silly. Why don't just use the eksctl upgrade command? Doesn't it support a rolling upgrade or it will bring in downtime for the user's application? Thanks.

**Comment by potatochun** [comment]
In my opinion, this tool is useful if you operate the EKS cluster via non-eksctl way. Some people might choose to run unmanaged worker nodes, which is then controlled via ASG. So this tool does the job nicely, in that sense.

**Comment by crhuber** [comment]
hi @openstacker , not everyone has provisioned their cluster using eks-ctl. Instead many have provisioned using terraform or another tool and have unmanaged worker nodes. So for that reason it still exists. I couldn't see any way using eksctl to update unmanaged worker nodes in a gradual fashion. I'm happy to be corrected so feel free to re-open if there is a way to do it with unmanaged nodes.
