### ISSUE TITLE
Batching of scale-up?

### ISSUE THREAD

**Issue by caphrim007** [hellofresh/eks-rolling-update#60]
Hi,

I've found that periodically the reliability of scale-up can be questionable in AWS. In particular, I've seen cases where the EC2 node never registers with the EKS cluster when doing a large amount of scaling (for instance 100+ nodes at once). This results in eks-rolling-update blocking indefinitely because the k8s node count never matches the EC2 count.

I modified eks-rolling-update to include a batch-count environment variable that allows me to instruct the tool to scale up X nodes at a time. This has appeared to eliminate the flakiness that I experience.

I would like to send a PR for the enhancement, but thought I should ask if the owners of this repo would even be interested before I make the PR. My implementation defaults to batching being optional.

Lemme know. Thanks.

**Comment by crhuber** [comment]
@caphrim007 Yes, it would be a welcome addition as we have also experience in the past situation where the control plane couldn't handle the amount of new nodes added at one time. So batching is something we would look forward to. Also just FYI, you can use mode 1 which will scale up and terminate one by one.

**Comment by caphrim007** [comment]
@crhuber thanks for the guidance, I'll open a follow-up PR

**Comment by crhuber** [comment]
Implemented here https://github.com/hellofresh/eks-rolling-update/pull/68
