### ISSUE TITLE
Wrong user when running eks_rolling_update script on a separate cluster

### ISSUE THREAD

**Issue by withoutnickname** [hellofresh/eks-rolling-update#81]
Hi!

We've implemented eks-rolling-update script as a separate stage in our CI (Gitlab).
There are 2 clusters involved: 
- "_gitlab-runners_" cluster, where script is executed inside Gitlab runner
- "_dev_" cluster, destination cluster that script must affect

Once script is executed inside Gitlab runner, we receive the following permissions-related error:
```
$ eks_rolling_update.py --cluster_name ${TF_VAR_cluster_name}
2020-12-10 13:28:28,187 INFO     Describing autoscaling groups...
2020-12-10 13:28:28,194 INFO     Pausing k8s autoscaler...
2020-12-10 13:28:28,203 INFO     Scaling of k8s autoscaler failed. Error code was Forbidden, {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.apps \"cluster-autoscaler\" is forbidden: User \"system:serviceaccount:eks:default\" cannot patch resource \"deployments\" in API group \"apps\" in the namespace \"kube-system\"","reason":"Forbidden","details":{"name":"cluster-autoscaler","group":"apps","kind":"deployments"},"code":403}
. Exiting.
```
That user `"system:serviceaccount:eks:default"` belongs to "_gitlab-runners_" cluster, not to "_dev_" (`eks` namespace exists only in "_gitlab-runners_" cluster). Moreover, if we get inside this Gitlab runner's container and scale autoscaler manually - all works fine, deployment in "_dev_" cluster scales up&down:
![rolling-update-1](https://user-images.githubusercontent.com/35262641/101783839-cc1c0700-3b0b-11eb-995d-eb7c66415d08.png)
That means kubeconfig file and AWS credentials are configured properly.

Note, locally eks_rolling_update.py works fine as well (with the same variables and creds which are used in CI).

Below is our eks-rolling-upgrade stage in Gitlab CI (`aws cli`, `kubectl` and `eks-rolling-update` already preinstalled in image):
```yaml
upgrade:
  stage: rolling-upgrade
  variables:
    AWS_DEFAULT_REGION: "eu-west-1"
    K8S_AUTOSCALER_ENABLED: "true"
    GLOBAL_MAX_RETRY: 20
    K8S_AUTOSCALER_NAMESPACE: "kube-system"
    K8S_AUTOSCALER_DEPLOYMENT: "cluster-autoscaler"
    K8S_AUTOSCALER_REPLICAS: 2
    KUBECONFIG: "/root/.kube/config"
  script:
    - source variables
    - aws eks --region eu-west-1 update-kubeconfig --name ${TF_VAR_cluster_name}
    - eks_rolling_update.py --cluster_name ${TF_VAR_cluster_name}
  when: manual
  timeout: 4h
```

If any additional details are needed, please let me know.
Looking forward to your reply.
Thanks in advance!

**Version of eks-rolling-update**: most recent (10-Dec-2020)
**version of Kubernetes**: 1.18

**Comment by crhuber** [comment]
Can you try setting `K8S_CONTEXT` perhaps the `current-context` is not what you are expecting

**Comment by withoutnickname** [comment]
@crhuber hi!
Thanks for quick reaction.
Unfortunately, setting `K8S_CONTEXT` variable didn't help.
I'm displaying _kubeconfig_ file during the pipeline to confirm it's correct. Actually it's absolutely identical to my local one.

Interesting observation: when I switch pipeline to a separate test Gitlab runner, located in new namespace in "_gitlab-runners_" cluster, let it be `eks2`, user in error message is updated accordingly from `"system:serviceaccount:eks:default"` to `"system:serviceaccount:eks2:default"`. 
Somehow script ignores the only existing _kubeconfig_ file with correct values and tries to perform changes with default authorization methods. Or not? What do you think?

**Comment by crhuber** [comment]
Is your ci also running in kubernetes? It loads the in cluster config first https://github.com/hellofresh/eks-rolling-update/blob/master/eksrollup/lib/k8s.py#L13

**Comment by withoutnickname** [comment]
Yes, CI is in Kubernetes. Then how to deal with that?

**Comment by chadlwilson** [comment]
Our CI is in Kubernetes (different cluster to target) and the change to default to in-cluster config caused issues for us too. The workaround was to disable automounting the serviceaccount token in our CI agent pods, so it falls back to regular kube config/context. We had no need for that token inside our agent pods, but if you need this for some other reason, I imagine you could have issues.

**Comment by withoutnickname** [comment]
@chadlwilson thanks a lot for the hint! 
I've added `automountServiceAccountToken: false` to the default service account and it worked.
