### ISSUE TITLE
Question - Throttling request took 2.429459004s

### ISSUE THREAD

**Issue by infa-ddeore** [hellofresh/eks-rolling-update#93]
this isnt a bug or any issue.

what is meaning of below log that comes during the script run sometimes, do we need to find what request is throttled?

```
I0209 21:27:49.835447   59139 request.go:645] Throttling request took 2.429459004s, request: GET:https://xxxxxxxxxxxxxxx.gr7.us-west-2.eks.amazonaws.com/api/v1/namespaces/xxxxx-yyyy/pods/aaa-bbb-ccc-dddd-6b4f44c7f8-vtsr2
```

**Comment by chadlwilson** [comment]
It would be helpful if you would include the context of what the tool was doing at the same of this log, but given it is a Golang log, I imagine it's coming from `kubectl` during drain?

If so, what is your `kubectl` version?

**Comment by infa-ddeore** [comment]
i thought its the eks rolling update logs, i can dig at kubectl side

thx for the pointer

**Comment by chadlwilson** [comment]
eks-rolling-update relies on `kubectl` to drain nodes because this is only implemented client-side in `kubectl` currently. But if it wasn't draining nodes at that point, then it might be something else
